version: "3.8"
services:
  app:
    build: .
    container_name: ai-customer-support-agent
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY="${OPENAI_API_KEY}"
    # env_file:
    #   - .env
